# -*- coding: utf-8 -*-
"""DAY 3v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZ9s2uv51yoAQi5Xh5IitM1i58t766lM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/Walmart Data Analysis and Forcasting.csv")

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.nunique()

df.duplicated().sum()

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)

# Sales trend
df.groupby('Date')['Weekly_Sales'].sum().plot(figsize=(12,5))

# Holiday vs Non-Holiday
sns.boxplot(x='Holiday_Flag', y='Weekly_Sales', data=df)

# Store-wise sales
df.groupby('Store')['Weekly_Sales'].sum().plot(kind='bar')

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Extract numerical features from 'Date'
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

# Features and Target
X = df.drop(["Weekly_Sales", "Date"], axis=1) # Drop original 'Date' column
y = df["Weekly_Sales"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
rf = RandomForestRegressor(n_estimators=200,random_state=42,n_jobs=-1)

rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

plt.figure(figsize=(8,6))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Weekly Sales")
plt.ylabel("Predicted Weekly Sales")
plt.title("Actual Weekly Sales vs Predicted Weekly Sales")
plt.axline([0,0],[1,1],color="red",linestyle
           ="--")
plt.show()

from scipy.stats import skew
skewness = df.skew(numeric_only=True)
num_cols = len(df.columns)
print(skewness)

import numpy as np
skewed_cols = df.skew(numeric_only=True).abs()
highly_skewed = skewed_cols[skewed_cols > 1].index
negatively_skewed = skewed_cols[skewed_cols < 1].index
print("Highly Skewed Columns: \n",highly_skewed)
print("Negatively Skewed Columns: \n",negatively_skewed)

df[highly_skewed] = df[highly_skewed].apply(lambda x: np.log1p(x))

from sklearn.preprocessing import PowerTransformer
pt = PowerTransformer(method="yeo-johnson")
df[negatively_skewed] = pt.fit_transform(df[negatively_skewed])

# Features and Target
X = df.drop(["Weekly_Sales", "Date"], axis=1) # Drop original 'Date' column
y = df["Weekly_Sales"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
rf = RandomForestRegressor(n_estimators=200,random_state=42,n_jobs=-1)

rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

