# -*- coding: utf-8 -*-
"""ML_day2(preprocessing test).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MWAeCPcV_T7ZDAcAcp3MseQ39HkM7Mr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/sample_data/preprocessing_practice_dataset.csv')
df_original = df.copy()

df.head()

df.isnull().sum()

df['Age_mean_imputted'] = df['Age'].fillna(df['Age'].mean())

df["Monthly_Salary"].fillna(df["Monthly_Salary"].median(), inplace=True)
df["Department"].fillna(df["Department"].mode()[0], inplace=True)
df["Education"].fillna(df["Education"].mode()[0], inplace=True)
df["City"].fillna(df["City"].mode()[0], inplace=True)

df.isnull().sum()

sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Age',y='City',palette='pastel')

plt.title('Boxplot of City by Age',fontsize=16)
plt.xlabel('Age ',fontsize=12)
plt.ylabel('City',fontsize=12)
plt.show()

sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.barplot(data=df,x='City',y='Age',palette='pastel')

plt.title('Bar Plot of Age by City',fontsize=16)
plt.xlabel('City ',fontsize=12)
plt.ylabel('Age',fontsize=12)
plt.show()

sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='City',y='Age',palette='pastel')

plt.title('Scatter Plot of Age by City',fontsize=16)
plt.xlabel('City ',fontsize=12)
plt.ylabel('Age',fontsize=12)
plt.show()

sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.barplot(data=df,x='Experience_Years',y='Monthly_Salary',palette='pastel')

plt.title('Barplot of Monthly_Salary by Experience_Years',fontsize=16)
plt.xlabel('Experience_Years ',fontsize=12)
plt.ylabel('Monthly_Salary',fontsize=12)
plt.show()

sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Experience_Years',y='Monthly_Salary',palette='pastel')

plt.title('Box plot of Monthly_Salary by Experience_Years',fontsize=16)
plt.xlabel('Experience_Years ',fontsize=12)
plt.ylabel('Monthly_Salary',fontsize=12)
plt.show()

from sklearn.preprocessing import LabelEncoder
encoded_data = df.copy()

one_hot_encoding = pd.get_dummies(encoded_data['Gender'], prefix='Gender')
encoded_data = pd.concat([encoded_data, one_hot_encoding], axis=1)

encoded_data

print(encoded_data["Attrition"].unique())

yes_no_mapper = {"No":0,"Yes":1}
encoded_data["Attrition"] = encoded_data["Attrition"].map(yes_no_mapper)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_cols = [
    "Age_mean_imputted",
    "Experience_Years",
    "Monthly_Salary",
    "Performance_Rating"
]
encoded_data[num_cols] = scaler.fit_transform(encoded_data[num_cols])

encoded_data