# -*- coding: utf-8 -*-
"""ML day 1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nI4L22OwlvL_rk7kHMJ053phGMCU2adC
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/titanic uncleaned.csv")

df.head()

df.describe()

df.isnull()

df.isnull().sum()

df['Age_mean_imputted'] = df['Age'].fillna(df['Age'].mean())
df['Age_median_imputted'] = df['Age'].fillna(df['Age'].median())

df

df['Cabin_mode_imputted'] = df['Cabin'].fillna(df['Cabin'].mode()[0])

df

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Embarked',y='Fare',palette='pastel')

plt.title('Boxplot of Fare by Embarked',fontsize=16)
plt.xlabel('Embarked ',fontsize=12)
plt.ylabel('Fare',fontsize=12)
plt.show()

from sklearn.preprocessing import LabelEncoder
encoded_data = df.copy()

#Label Encoding for 'Sex'
label_encoder = LabelEncoder()
encoded_data['Sex_Label'] = label_encoder.fit_transform(encoded_data['Sex'])

#One-Hot Encoding for 'Embarked'
one_hot_encoding = pd.get_dummies(encoded_data['Embarked'], prefix='Embarked')
encoded_data = pd.concat([encoded_data, one_hot_encoding], axis=1)

#Since 'Pclass' is ordinal, we can create a mapped column for demo
pclass_mapping = {1: 'First', 2: 'Second', 3: 'Third'}
#Ordinal Encoding for p class
encoded_data['Pclass_Category'] = encoded_data['Pclass'].map(pclass_mapping)

# Display the resulting dataset with relevant encoded columns
print(encoded_data[['Sex', 'Sex_Label', 'Embarked', 'Embarked_Q', 'Embarked_S', 'Embarked_C', 'Pclass', 'Pclass_Category']].head())
\