# -*- coding: utf-8 -*-
"""DAY 3v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZ9s2uv51yoAQi5Xh5IitM1i58t766lM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/Walmart Data Analysis and Forcasting.csv")

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.nunique()

df.duplicated().sum()

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)

df.groupby('Date')['Weekly_Sales'].sum().plot(figsize=(12,5))

sns.boxplot(x='Holiday_Flag', y='Weekly_Sales', data=df)

df.groupby('Store')['Weekly_Sales'].sum().plot(kind='bar')

plt.figure(figsize=(8,5))
sns.histplot(df['Weekly_Sales'],
             bins=30,
             kde=True)

plt.title("Distribution of Weekly Sales")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Temperature',
    y='Weekly_Sales',
    data=df
)

plt.title("Temperature vs Weekly Sales")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Fuel_Price',
    y='Weekly_Sales',
    data=df
)

plt.title("Fuel Price vs Weekly Sales")
plt.show()

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Month'] = df['Date'].dt.month
monthly_sales = df.groupby('Month')['Weekly_Sales'].mean()

plt.figure(figsize=(8,5))
monthly_sales.plot(marker='o')

plt.title("Average Monthly Sales")
plt.ylabel("Sales")
plt.show()

df['Quarter'] = df['Date'].dt.quarter
quarterly_sales = df.groupby('Quarter')['Weekly_Sales'].mean()

plt.figure(figsize=(8,5))
quarterly_sales.plot(kind='bar')

plt.title("Quarterly Average Sales")
plt.ylabel("Sales")
plt.show()

top10 = (df.groupby('Store')['Weekly_Sales']
           .sum()
           .sort_values(ascending=False)
           .head(10))

plt.figure(figsize=(10,5))
top10.plot(kind='bar')

plt.title("Top 10 Stores by Total Sales")
plt.ylabel("Sales")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

X = df.drop(["Weekly_Sales", "Date"], axis=1)
y = df["Weekly_Sales"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(n_estimators=200,random_state=42,n_jobs=-1)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

plt.figure(figsize=(8,6))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Weekly Sales")
plt.ylabel("Predicted Weekly Sales")
plt.title("Actual Weekly Sales vs Predicted Weekly Sales")
plt.axline([0,0],[1,1],color="red",linestyle
           ="--")
plt.show()

from scipy.stats import skew
skewness = df.skew(numeric_only=True)
num_cols = len(df.columns)
print(skewness)

import numpy as np
skewed_cols = df.skew(numeric_only=True).abs()
highly_skewed = skewed_cols[skewed_cols > 1].index
negatively_skewed = skewed_cols[skewed_cols < 1].index
print("Highly Skewed Columns: \n",highly_skewed)
print("Negatively Skewed Columns: \n",negatively_skewed)

df[highly_skewed] = df[highly_skewed].apply(lambda x: np.log1p(x))

from sklearn.preprocessing import PowerTransformer

negatively_skewed_features_list = [col for col in negatively_skewed if col != 'Weekly_Sales']
pt_features = PowerTransformer(method="yeo-johnson")
df[negatively_skewed_features_list] = pt_features.fit_transform(df[negatively_skewed_features_list])

pt_target = PowerTransformer(method="yeo-johnson")
df['Weekly_Sales'] = pt_target.fit_transform(df[['Weekly_Sales']])

X = df.drop(["Weekly_Sales", "Date"], axis=1)
y = df["Weekly_Sales"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(n_estimators=200,random_state=42,n_jobs=-1)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

plt.figure(figsize=(8,6))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Weekly Sales")
plt.ylabel("Predicted Weekly Sales")
plt.title("Actual Weekly Sales vs Predicted Weekly Sales")
plt.axline([0,0],[1,1],color="red",linestyle
           ="--")
plt.show()

sample_input_data = pd.DataFrame([{
    'Store': 1,
    'Holiday_Flag': 1,
    'Temperature': 38.51,
    'Fuel_Price': 2.548,
    'CPI':211.242170,
    'Unemployment': 8.106,
    'Year': 2010,
    'Month': 2,
    'Day': 12,
    'Quarter': 1
}])

sample_input_data[highly_skewed] = sample_input_data[highly_skewed].apply(lambda x: np.log1p(x))

features_for_pt = ['Store', 'Temperature', 'Fuel_Price', 'CPI', 'Month', 'Quarter', 'Year', 'Day']
sample_input_data[features_for_pt] = pt_features.transform(sample_input_data[features_for_pt])
sample_input_data = sample_input_data[X_train.columns]
predicted_sales_transformed = rf.predict(sample_input_data)

original_scale_prediction = pt_target.inverse_transform(predicted_sales_transformed.reshape(-1, 1))[0][0]

print(f"Predicted Weekly Sales (Original Scale): {original_scale_prediction:.2f}")

