# -*- coding: utf-8 -*-
"""ML day 2v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duV-tlgN2JXnhIoMTC-u8-fd2RX5k1x-
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/boston (1).csv")

df.shape

df.info()

df.describe()

df.duplicated().sum()

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.barplot(data=df,x='ptratio',y='age',palette='pastel')

plt.title('Boxplot of ptratio by age',fontsize=16)
plt.xlabel('ptratio ',fontsize=8)
plt.ylabel('age',fontsize=8)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style= "whitegrid")

plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='lstat',y='medv',palette='pastel')

plt.title('Boxplot of medv by lstat',fontsize=16)
plt.xlabel('medv ',fontsize=8)
plt.ylabel('lstat',fontsize=8)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sns.histplot(df["medv"], kde=True)
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score


X = df.drop(columns=["medv"])
y = df["medv"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

rmse = mean_squared_error(y_test, y_pred) ** 0.5
print("RMSE:", rmse)
